/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddImport } from './routes/add'
import { Route as RestaurantIdIndexImport } from './routes/restaurant.$id.index'
import { Route as RestaurantIdRateImport } from './routes/restaurant.$id.rate'
import { Route as RestaurantIdAddVisitImport } from './routes/restaurant.$id.add-visit'

// Create/Update Routes

const AddRoute = AddImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantIdIndexRoute = RestaurantIdIndexImport.update({
  path: '/restaurant/$id/',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantIdRateRoute = RestaurantIdRateImport.update({
  path: '/restaurant/$id/rate',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantIdAddVisitRoute = RestaurantIdAddVisitImport.update({
  path: '/restaurant/$id/add-visit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddImport
      parentRoute: typeof rootRoute
    }
    '/restaurant/$id/add-visit': {
      id: '/restaurant/$id/add-visit'
      path: '/restaurant/$id/add-visit'
      fullPath: '/restaurant/$id/add-visit'
      preLoaderRoute: typeof RestaurantIdAddVisitImport
      parentRoute: typeof rootRoute
    }
    '/restaurant/$id/rate': {
      id: '/restaurant/$id/rate'
      path: '/restaurant/$id/rate'
      fullPath: '/restaurant/$id/rate'
      preLoaderRoute: typeof RestaurantIdRateImport
      parentRoute: typeof rootRoute
    }
    '/restaurant/$id/': {
      id: '/restaurant/$id/'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AddRoute,
  RestaurantIdAddVisitRoute,
  RestaurantIdRateRoute,
  RestaurantIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/add",
        "/restaurant/$id/add-visit",
        "/restaurant/$id/rate",
        "/restaurant/$id/"
      ]
    },
    "/add": {
      "filePath": "add.tsx"
    },
    "/restaurant/$id/add-visit": {
      "filePath": "restaurant.$id.add-visit.tsx"
    },
    "/restaurant/$id/rate": {
      "filePath": "restaurant.$id.rate.tsx"
    },
    "/restaurant/$id/": {
      "filePath": "restaurant.$id.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
